### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ByTanimsiz** [ipwnosx/KeyAuth-Leak-Source-Code#1]
https://cdn.discordapp.com/attachments/696445958170607748/855134533695176714/Ekran_Alnts22222.PNG
how can i create key like there

**Comment by ipwnosx** [comment]
idk man.. i don't provide support. I'm just sharing  a leak. so.. that's up to u to figure out

**Comment by ByTanimsiz** [comment]
> idk man.. i don't provide support. I'm just sharing a leak. so.. that's up to u to figure out

i fixed the error

**Comment by ipwnosx** [comment]
Ok
